name: My First workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: welcome message
              run: echo "action job 1"

            - name: list files
              run: ls

            - name: cat file
              run: cat readme.md
