name: My Second workflow

on: push

jobs:
    second_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Executing shell script
              run: ./ascii-script.sh
